#!/bin/bash
# This script grabs from all topics installation file (install.sh)
# Then run them, one by one

set -e

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

install_topic () {
  info "Installing $1..."

  bash "$1" || true

  success "$1 Installed"
}

find . -maxdepth 2 -name install.sh | while read path ; do install_topic "$path" ; done
